---
title: "Class activtiy for shirt breakfast"
output: html_document
date: "2022-09-20"
---
```{r}
#color <- "red"
#color <- "yellow"
color <- "blue"
#color <- "green"
#color <- "orange"
#color <- "white
```

```{r}

if(color=="yellow"){
  print("bannana")       
} else if(color=="green"){
  print("Green Apple")  
} else if(color=="red"){
  print("Red Apple")     
} else if(color=="blue"){ 
  print("Lolipop")      
}else if(color=="orange"){
  print("orange")    
}else if(color=="white") 
  {print("milk")            
}else {print("no food")}
```
```{r}
stop <- sample(1:1000,1)
num=0
while (num<0){
  print("pop goes the weasel")
}
  
}
```
Remove junk characters
Split up lists of ID's 
Revectorize to individual ID's, currently vector of lists of characters
```{r}
list1<- gsub("\\[","",Test_V_output$`Paper ID`)
list2<-gsub("\\]","",list1)
list3<- gsub("\'","",list2)
list4 <- gsub(" ", "", list3)
```

```{r}
split_ID <- unlist(strsplit(list4, ","))
```


```{r}
length(unique(split_ID))
```

