---
title: "Low_High_Mut_R"
output: html_document
date: "2022-10-31"
---
#uploading data and defining a column 
```{r}
SeqData <- read.table('//Users/nagendra//Desktop//Bioinformatics//Project//Data//ACTG5257_RT_fasta.txt',header=FALSE,fill=TRUE) 
WeekNumber <- SeqData$V1

```

https://blast.ncbi.nlm.nih.gov/Blast.cgi?BLAST_SPEC=blast2seq&LINK_LOC=align2seq&PAGE_TYPE=BlastSearch 

INDEXING solution***

```{r}
idx <- c()
#trying to move sequences for day0 and end day for each patient to a different dataframe
#Loop comments
#making sure the patient names are the same, the day for the row is 0 
#making sure the indexed box is not empty or NA
for(h in 1:length(SeqData$V1)){
  if(SeqData$V5[h]==SeqData$V5[h+2] && SeqData$V8[h] == 0 && is.na(SeqData$V8[h])==FALSE && SeqData$V5[h]!= "" && SeqData$V8[h]!=SeqData$V8[h+2]){
    #if all those conditions are met, the row number is indexed and saved in idx
    idx <- append(idx, h)
  }
}
  
StartSeq<- SeqData$V1[idx+1]
EndSeq <- SeqData$V1[idx+3]
PTID <- SeqData$V5[idx]
StartDayNumber <- SeqData$V8[idx]
EndDayNumber <- SeqData$V8[idx+2]

```

Making a dataframe with the saved rows
```{r}
CompleteDF <- data.frame(StartSeq, EndSeq, PTID, StartDayNumber, EndDayNumber)
```

Removing periods before nucleotide sequences
```{r}
CompleteDF$StartSeq <- gsub("\\.","", CompleteDF$StartSeq)
CompleteDF$EndSeq <- gsub("\\.","", CompleteDF$EndSeq)
```

Saving dataframe to a text file
```{r}

write.table(CompleteDF,'/Users/nagendra/Desktop/Bioinformatics/Project/Data/DataForBLAST.csv', sep = ",")
```

Updating blast sequence data
```{r}
BLAST <- read.table('/Users/nagendra/Desktop/Bioinformatics/Project/Data/BLASTFinalAlignment.csv', sep= ",")
```
Getting Blast sequences cleaned up 
```{r}
ydx<-c()
for(z in 1:length(BLAST$V1)){
  if(BLAST$V1[z]==BLAST$V2[z]){
   ydx <- append(ydx,z) 
  }
}

PatientName <- BLAST$V1[ydx]
SimilarityPct <- BLAST$V3[ydx]
BPlength <- BLAST$V4[ydx]

```

Making comparison BLAST dataframe
```{r}
BLASTCompare <- data.frame(PatientName, SimilarityPct, BPlength, EndDayNumber)
```

Trouble shooting
```{r}
numYes <- c(0)
numNo <- c(0)
for(s in 1:242){
  if(BLASTCompare$PatientName[s] == CompleteDF$PTID[s]){
    numYes <- numYes + 1
  }else{
    numNo <- numNo + 1
  }
}
```

